# Generated by Django 4.0.3 on 2022-04-07 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Choose grade', max_length=1)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(help_text='Enter a brief description of the hotel room', max_length=500)),
                ('area', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(help_text='Enter a type hotel room', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип комнаты',
                'verbose_name_plural': 'Типы комнат',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this room', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Room availability', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hotel.room')),
            ],
            options={
                'verbose_name': 'Экземпляр комнаты',
                'verbose_name_plural': 'Экземпляры комнат',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(help_text='select a type for this hotel room', on_delete=django.db.models.deletion.CASCADE, to='Hotel.type'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(help_text='Enter your name.', max_length=30)),
                ('surname', models.TextField(help_text='Enter your surname.', max_length=35)),
                ('text', models.TextField(help_text='Enter your comment about Hotel', max_length=2000)),
                ('create_review_date', models.DateField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.grade')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(help_text='Enter your name.', max_length=30)),
                ('surname', models.TextField(help_text='Enter your surname.', max_length=35)),
                ('birthday', models.DateField()),
                ('arrival_date', models.DateField()),
                ('date_of_departure', models.DateField()),
                ('phone_number', models.IntegerField(help_text='Enter your number phone')),
                ('email', models.EmailField(help_text='Enter your email', max_length=254)),
                ('pay_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.paymethod')),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.roominstance')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['arrival_date', 'date_of_departure', 'surname'],
            },
        ),
    ]
